name: james_shop
description: "This is james shop"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  flutter_spinkit: ^5.2.0
  loading_indicator: ^3.1.1
  flutter_svg: ^2.0.9
  logging: ^1.2.0
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.0
  pull_to_refresh: ^2.0.0
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.27.0
  flutter_facebook_auth: ^6.2.0
  google_sign_in: ^6.1.0
  firebase_auth: ^4.17.8
  dio: ^5.4.2+1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  flutter_flavorizr: ^2.2.3

flavorizr:
  flavors:
    dev:
      app:
        name: "James Shop Dev"
      android:
        applicationId: "com.james.dev"
      ios:
        bundleId: "com.james.dev"
    prod:
      app:
        name: "James Shop"
      android:
        applicationId: "com.james.prod"
      ios:
        bundleId: "com.james.prod"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/svg_images/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/urbanist/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/urbanist/Urbanist-ExtraBold.ttf
          weight: 800
